version: "3"
services:
  app:
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
  frontend:
    stdin_open: true
    tty: true
    build:
      context: ../spedhub-frontend
      args:
        UID: ${UID:-1000}
    volumes:
      - ../spedhub-frontend:/usr/src/app
    ports:
      - 8081:8081
    command: yarn serve --port 8081
    user: frontend

  postgres:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
