version: "3"
services:
  app:
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
  frontend:
    build:
      context: ../spedhub-frontend
      args:
        UID: ${UID:-1000}
    volumes:
      - ../spedhub-frontend:/app
    ports:
      - 8080:8080
    command: yarn run serve
    user: frontend

  postgres:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
